### ISSUE TITLE
GET requests are broken

### ISSUE THREAD

**Issue by chariskar** [EarthMC/EMCAPI#19]
since the addition of POST templates, querrying is not working anymore i cant tell if its intented or not

**Comment by jwkerr** [comment]
query parameters are replaced with request bodies and will be what is used in the stable v3 release, read /docs in this repo for help

**Comment by chariskar** [comment]
but why

**Comment by Mhmdkbz** [comment]
More stable and efficient. GET method isnt as good as the others out there. This is simply more efficient

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
